name: dependabot-merges

on:
  pull_request:

jobs:
  auto-merge-patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch # Merge patch updates
          github-token: ${{ secrets.WORKFLOW_TOKEN }}

  auto-merge-minor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor # Merge minor updates
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
